feat oidc

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -49,6 +49,41 @@ commands:
 
             aws sts get-caller-identity
 
+  aws-authentication-docker:
+    steps:
+      - run:
+          name: Authenticate with AWS OIDC
+          command: |
+            apt add --no-cache curl jq aws-cli
+            echo "${CIRCLE_OIDC_TOKEN}" > /tmp/token.jwt || true
+            export AWS_ROLE_ARN="arn:aws:iam::183631319967:role/sagar-oidc"
+            export AWS_WEB_IDENTITY_TOKEN_FILE="/tmp/token.jwt"
+
+            aws sts assume-role-with-web-identity \
+                  --role-arn "$AWS_ROLE_ARN" \
+                  --role-session-name "CircleCIJob" \
+                  --web-identity-token "$(cat $AWS_WEB_IDENTITY_TOKEN_FILE)" \
+                  --duration-seconds 3600 > /tmp/aws-credentials.json
+
+            AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' /tmp/aws-credentials.json)
+            AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' /tmp/aws-credentials.json)
+            AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' /tmp/aws-credentials.json)
+
+            if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_SESSION_TOKEN" ]; then
+              echo "ERROR: AWS credentials not retrieved properly"
+              exit 1
+            fi
+
+            echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $BASH_ENV
+            echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $BASH_ENV
+            echo "export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $BASH_ENV
+            echo "export AWS_REGION=ap-south-1" >> $BASH_ENV
+            echo "export AWS_DEFAULT_REGION=ap-south-1" >> $BASH_ENV
+            source $BASH_ENV
+
+            aws sts get-caller-identity
+
+
 jobs:
   say-hello:
     docker:
@@ -114,7 +149,7 @@ jobs:
     steps:
       - checkout
       - setup_remote_docker
-      - aws-authentication
+      - aws-authentication-docker
       - run:
           name: Authenticate with AWS ECR
           command: |
@@ -133,7 +168,7 @@ jobs:
       - image: circleci/python:latest
     steps:
       - checkout
-      - aws-authentication
+      - aws-authentication-docker
       - run:
           name: Configure AWS CLI & EKS Access
           command: |
